[env:genericSTM32F103C8]
platform = ststm32
board = genericSTM32F103C8
framework = arduino   ; or stm32cube if you prefer HAL/LL

upload_protocol = stlink
debug_tool = stlink
build_flags = -DUSBCON -DUSBD_USE_CDC -DHSE_VALUE=16000000U
monitor_speed = 9600