[env:genericSTM32F103C8]
platform = ststm32
board = genericSTM32F103C8
framework = arduino   ; or stm32cube if you prefer HAL/LL

upload_protocol = stlink
debug_tool = stlink

monitor_speed = 9600

build_unflags = 
    -std=gnu++11
    -std=gnu++17

build_flags =
    -std=gnu++20
    -DUSBCON
    -DUSBD_USE_CDC
    -DHSE_VALUE=16000000U